# CCG 
# Ansible integration demo
name: Ansible integration
formatVersion: 1
inputs: {}
resources:
  Cloud_Ansible_1:
    type: Cloud.Ansible
    metadata:
      layoutPosition:
        - 0
        - 0
    properties:
      host: '${resource.Cloud_vSphere_Machine_1.*}'
      osType: linux
      account: Iberia.local ansible
      username: root
      password: 
      playbooks:
        provision:
          - /root/playbooks/linux-apache.yml
  Cloud_vSphere_Machine_1:
    type: Cloud.vSphere.Machine
    metadata:
      layoutPosition:
        - 0
        - 1
    properties:
      folderName: Howarts Cloud
      image: C101VRA01CentOS
      flavor: C101VRA01Small
      networks:
        - network: '${resource.Cloud_vSphere_Network_1.id}'
          assignment: static
  Cloud_vSphere_Network_1:
    type: Cloud.vSphere.Network
    metadata:
      layoutPosition:
        - 1
        - 0
    properties:
      networkType: existing
      constraints:
        - tag: 'nettype:Management'
